// 1.Arithmetic Operators:
// + (Addition): Adds two values.
// - (Subtraction): Subtracts the right operand from the left operand.
// * (Multiplication): Multiplies two values.
// / (Division): Divides the left operand by the right operand.
// % (Modulus): Returns the remainder of the division of the left operand by the right operand.

let a = 5;   // EXAMPLE:
let b = 2;
let result = a + b; // result will be 7


// 2.Comparison Operators:
// == (Equal to): Compares if two values are equal.
// === (Strict equal to): Compares if two values are equal without type conversion.
// != (Not equal to): Compares if two values are not equal.
// !== (Strict not equal to): Compares if two values are not equal without type conversion.
// > (Greater than): Checks if the left operand is greater than the right operand.
// < (Less than): Checks if the left operand is less than the right operand.
// >= (Greater than or equal to): Checks if the left operand is greater than or equal to the right operand.
// <= (Less than or equal to): Checks if the left operand is less than or equal to the right operand.


let x=2    // EXAMPLE:
let y="2"
console.log(x===y) //ans is false

// 3.Logical Operators:
// && (Logical AND): Returns true if both operands are true.
// || (Logical OR): Returns true if at least one of the operands is true.
// ! (Logical NOT): Returns true if the operand is false, and vice versa.

let condition1 = true;//EXAMPLE
let condition2 = false;
console.log(condition1 && condition2); // Output: false


// 4.Assignment Operators:
// = (Assignment): Assigns the value of the right operand to the left operand.
// +=, -=, *=, /=: Perform the corresponding arithmetic operation and assign the result to the left operand.

let a = 5; //example
a += 3; // ANS will be 8 